module.exports = {
  apps: [
    {
      name: 'agentcore-api',
      cwd: './apps/api',
      script: 'server.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      max_restarts: 10,
      min_uptime: '30s',
      kill_timeout: 5000,
      listen_timeout: 15000,
      shutdown_with_message: true,
      env: {
        NODE_ENV: 'production',
        PORT: 4000,
        CLIENT_URL: 'https://agentcore.work',
      },
      error_file: '/var/log/agentcore-api-error.log',
      out_file: '/var/log/agentcore-api.log',
      log_file: '/var/log/agentcore-api-combined.log',
      merge_logs: true,
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      log_type: 'json',
      max_size: '10M',
      rotate_interval: '0 0 * * *',
      rotate_days: 14,
    },
    {
      name: 'agentcore-web',
      cwd: './apps/web',
      script: 'next',
      args: 'start -p 3000',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      max_restarts: 15,
      restart_delay: 5000,
      min_uptime: '30s',
      kill_timeout: 10000,
      listen_timeout: 30000,
      shutdown_with_message: true,
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        NEXT_PUBLIC_API_URL: 'https://api.agentcore.work',
        CLIENT_URL: 'https://agentcore.work',
      },
      error_file: '/var/log/agentcore-web-error.log',
      out_file: '/var/log/agentcore-web.log',
      log_file: '/var/log/agentcore-web-combined.log',
      merge_logs: true,
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      log_type: 'json',
      max_size: '10M',
      rotate_interval: '0 0 * * *',
      rotate_days: 14,
    },
  ],
};
