import i18n from "@/i18n";

export const PLANS = [
  {
    id: "basic",
    name: i18n.t("billing.planNames.basic"),
    price: "20 000 ₽/мес",
    priceKopecks: 2000000,
    features: [
      i18n.t("billing.planFeatures.basic_3bots"),
      i18n.t("billing.planFeatures.basic_3people"),
      i18n.t("billing.planFeatures.basic_tokens"),
      i18n.t("billing.planFeatures.basic_integrations"),
      i18n.t("billing.planFeatures.basic_analyses"),
    ],
    apiLimit: 20000,
    maxAgents: 3,
    maxUsers: 3,
    maxTokens: 20_000_000,
    maxIntegrations: 80,
    maxAnalyses: 5,
    rateLimit: 500,
  },
  {
    id: "extended",
    name: i18n.t("billing.planNames.extended"),
    price: "45 000 ₽/мес",
    priceKopecks: 4500000,
    features: [
      i18n.t("billing.planFeatures.extended_8bots"),
      i18n.t("billing.planFeatures.extended_8people"),
      i18n.t("billing.planFeatures.extended_tokens"),
      i18n.t("billing.planFeatures.extended_integrations"),
      i18n.t("billing.planFeatures.extended_premiumSupport"),
      i18n.t("billing.planFeatures.extended_analyses"),
    ],
    apiLimit: 50000,
    maxAgents: 8,
    maxUsers: 8,
    maxTokens: 50_000_000,
    maxIntegrations: 999,
    maxAnalyses: 15,
    rateLimit: 2000,
  },
  {
    id: "premium",
    name: i18n.t("billing.planNames.premium"),
    price: "80 000 ₽/мес",
    priceKopecks: 8000000,
    features: [
      i18n.t("billing.planFeatures.premium_20bots"),
      i18n.t("billing.planFeatures.premium_50people"),
      i18n.t("billing.planFeatures.premium_unlimitedTokens"),
      i18n.t("billing.planFeatures.premium_integrations"),
      i18n.t("billing.planFeatures.premium_dedicatedSupport"),
      i18n.t("billing.planFeatures.premium_unlimitedAnalyses"),
    ],
    apiLimit: 999999,
    maxAgents: 20,
    maxUsers: 50,
    maxTokens: 999_999_999,
    maxIntegrations: 999,
    maxAnalyses: 999,
    rateLimit: 999999,
  },
  {
    id: "custom",
    name: i18n.t("billing.planNames.custom"),
    price: i18n.t("billing.planFeatures.custom_priceIndividual"),
    priceKopecks: 0,
    features: [
      i18n.t("billing.planFeatures.custom_unlimitedBots"),
      i18n.t("billing.planFeatures.custom_unlimitedPeople"),
      i18n.t("billing.planFeatures.custom_unlimitedTokens"),
      i18n.t("billing.planFeatures.custom_integrations"),
      i18n.t("billing.planFeatures.custom_personalManager"),
      i18n.t("billing.planFeatures.custom_customSla"),
    ],
    apiLimit: 999999,
    maxAgents: 999,
    maxUsers: 999,
    maxTokens: 999_999_999,
    maxIntegrations: 999,
    maxAnalyses: 999,
    rateLimit: 999999,
  },
];

export const PLAN_PRICES: Record<string, number> = {
  basic: 2000000,
  extended: 4500000,
  premium: 8000000,
};

export type PlanId = (typeof PLANS)[number]["id"];
